# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: main.app
    packRequirements: false
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http:
          path: /api/v1
          cors: true
          method: ANY
      - http:
          path: /api/v1/{proxy+}
          cors: true
          method: ANY
