"""empty message

Revision ID: 44f29cc259f8
Revises: e07dd5e4b2b7
Create Date: 2020-04-18 18:30:20.416740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f29cc259f8'
down_revision = 'e07dd5e4b2b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_vehicle_id_fkey', 'location', type_='foreignkey')
    op.create_foreign_key(None, 'location', 'location', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.create_foreign_key('location_vehicle_id_fkey', 'location', 'user', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###
