"""empty message

Revision ID: 949d019352cb
Revises: 44f29cc259f8
Create Date: 2020-04-18 18:30:45.193935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949d019352cb'
down_revision = '44f29cc259f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_vehicle_id_fkey', 'location', type_='foreignkey')
    op.create_foreign_key(None, 'location', 'vehicle', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.create_foreign_key('location_vehicle_id_fkey', 'location', 'location', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###
