"""empty message

Revision ID: dff0206dae13
Revises: 4a7a42596da2
Create Date: 2020-04-18 15:13:40.197406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff0206dae13'
down_revision = '4a7a42596da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('vehicle', 'longitude')
    op.drop_column('vehicle', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('vehicle', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
